// Generated by Copilot
import { z } from 'zod';

// --- Quotes ---
export const ZOptionQuoteFilter = z.object({
    optionType: z.enum(['Call', 'Put']).optional(),
    underlyingId: z.number(),
    expiryDate: z.string(),
    minstrikePrice: z.number().optional(),
    maxstrikePrice: z.number().optional(),
});
export const ZGetOptionQuotesRequest = z.object({
    filters: z.array(ZOptionQuoteFilter).optional(),
    optionIds: z.array(z.number()).optional(),
});

export const ZOptionQuote = z.object({
    underlying: z.string(),
    underlyingId: z.number(),
    symbol: z.string(),
    symbolId: z.number(),
    bidPrice: z.number(),
    bidSize: z.number(),
    askPrice: z.number(),
    askSize: z.number(),
    lastTradePriceTrHrs: z.number(),
    lastTradePrice: z.number(),
    lastTradeSize: z.number(),
    lastTradeTick: z.enum(['Up', 'Down', 'Equal']),
    lastTradeTime: z.string(),
    volume: z.number(),
    openPrice: z.number(),
    highPrice: z.number(),
    lowPrice: z.number(),
    volatility: z.number(),
    delta: z.number(),
    gamma: z.number(),
    theta: z.number(),
    vega: z.number(),
    rho: z.number(),
    openInterest: z.number(),
    delay: z.number(),
    isHalted: z.boolean(),
    VWAP: z.number(),
});
export const ZGetOptionQuotesResponse = z.object({
    optionQuotes: z.array(ZOptionQuote),
});
