// Generated by Copilot
export interface IGetAccountOrdersRequest {
    accountId: string;
    startTime?: string;
    endTime?: string;
    stateFilter?: 'All' | 'Open' | 'Closed';
    orderId?: number;
}
