// Generated by Copilot
export interface IAccount {
  type: string;
  number: string;
  status: string;
  isPrimary: boolean;
  isBilling: boolean;
  clientAccountType: string;
}

export interface IGetAccountsResponse {
  accounts: IAccount[];
  userId: number;
}
