// Generated by Copilot
export interface IPosition {
    symbol: string;
    symbolId: number;
    openQuantity: number;
    closedQuantity?: number;
    currentMarketValue: number;
    currentPrice: number;
    averageEntryPrice: number;
    closedPnl: number;
    openPnl: number;
    totalCost: number;
    isRealTime: boolean;
    isUnderReorg: boolean;
}

export interface IGetAccountPositionsResponse {
    positions: IPosition[];
}
