// Generated by Copilot
export interface IOrder {
    id: number;
    symbol: string;
    symbolId: number;
    totalQuantity: number;
    openQuantity: number;
    filledQuantity: number;
    canceledQuantity: number;
    side: string;
    orderType: string;
    limitPrice?: number;
    stopPrice?: number;
    isAllOrNone: boolean;
    isAnonymous: boolean;
    icebergQuantity?: number;
    minQuantity?: number;
    avgExecPrice?: number;
    lastExecPrice?: number;
    source: string;
    timeInForce: string;
    gtdDate?: string;
    state: string;
    clientReasonStr?: string;
    chainId: number;
    creationTime: string;
    updateTime: string;
    notes?: string;
    primaryRoute: string;
    secondaryRoute?: string;
    orderRoute: string;
    venueHoldingOrder?: string;
    commissionCharged: number;
    exchangeOrderId: string;
    isSignificantShareholder: boolean;
    isInsider: boolean;
    isLimitOffsetInDollar: boolean;
    userId: number;
    placementCommission?: number;
    strategyType: string;
    mainChainId?: number;
    legs: any[];
}

export interface IGetAccountOrdersResponse {
    orders: IOrder[];
}
