// Generated by Copilot
export interface IBalance {
    currency: string;
    cash: number;
    marketValue: number;
    totalEquity: number;
    buyingPower: number;
    maintenanceExcess: number;
    isRealTime: boolean;
}

export interface IGetAccountBalancesResponse {
    perCurrencyBalances: IBalance[];
    combinedBalances: IBalance[];
    sodPerCurrencyBalances: IBalance[];
    sodCombinedBalances: IBalance[];
}
