// Generated by Copilot
export interface IAccountActivity {
    tradeDate: string;
    transactionDate: string;
    settlementDate: string;
    action: string;
    symbol: string;
    symbolId: number;
    description: string;
    currency: string;
    quantity: number;
    price: number;
    grossAmount: number;
    commission: number;
    netAmount: number;
    type: string;
}

export interface IGetAccountActivitiesResponse {
    activities: IAccountActivity[];
}
