// Generated by Copilot
export interface IExecution {
    symbol: string;
    symbolId: number;
    quantity: number;
    side: string;
    price: number;
    id: number;
    orderId: number;
    orderChainId: number;
    exchangeExecId: string;
    timestamp: string;
    notes?: string;
    venue: string;
    totalCost: number;
    orderPlacementCommission: number;
    commission: number;
    executionFee: number;
    secFee: number;
    canadianExecutionFee: number;
    parentId: number;
}

export interface IGetAccountExecutionsResponse {
    executions: IExecution[];
}
