// Generated by Copilot
import { StrategyType } from '../enums/StrategyType';
import { OrderAction } from '../enums/OrderAction';

export interface IStrategyQuoteRequest {
    variants: IStrategyVariantRequest[];
}

export interface IStrategyVariantRequest {
    variantId: number;
    strategy: StrategyType;
    legs: IStrategyLeg[];
}

export interface IStrategyLeg {
    symbolId: number;
    action: OrderAction;
    ratio: number;
}
