// Generated by Copilot
export interface IStrategyQuote {
    variantId: number;
    bidPrice: number;
    askPrice: number;
    underlying: string;
    underlyingId: number;
    openPrice: number | null;
    volatility: number;
    delta: number;
    gamma: number;
    theta: number;
    vega: number;
    rho: number;
    isRealTime: boolean;
}

export interface IStrategyQuoteResponse {
    strategyQuotes: IStrategyQuote[];
}
