// Generated by Copilot
export interface IOptionQuoteFilter {
    optionType?: 'Call' | 'Put';
    underlyingId: number;
    expiryDate: string;
    minstrikePrice?: number;
    maxstrikePrice?: number;
}

export interface IGetOptionQuotesRequest {
    filters?: IOptionQuoteFilter[];
    optionIds?: number[];
}
