// Generated by Copilot
import { OptionType } from '../enums/OptionType';

export interface IOptionQuoteFilter {
  optionType?: OptionType;
  underlyingId: number;
  expiryDate: string;
  minstrikePrice?: number;
  maxstrikePrice?: number;
}

export interface IGetOptionQuotesRequest {
  filters?: IOptionQuoteFilter[];
  optionIds?: number[];
}
