// Generated by Copilot
import { TickType } from '../enums/TickType';

export interface IOptionQuote {
    underlying: string;
    underlyingId: number;
    symbol: string;
    symbolId: number;
    bidPrice: number;
    bidSize: number;
    askPrice: number;
    askSize: number;
    lastTradePriceTrHrs: number;
    lastTradePrice: number;
    lastTradeSize: number;
    lastTradeTick: TickType;
    lastTradeTime: string;
    volume: number;
    openPrice: number;
    highPrice: number;
    lowPrice: number;
    volatility: number;
    delta: number;
    gamma: number;
    theta: number;
    vega: number;
    rho: number;
    openInterest: number;
    delay: number;
    isHalted: boolean;
    VWAP: number;
}

export interface IGetOptionQuotesResponse {
    optionQuotes: IOptionQuote[];
}
