// Generated by Copilot
export interface IQuote {
    symbol: string;
    symbolId: number;
    tier?: string;
    bidPrice: number;
    bidSize: number;
    askPrice: number;
    askSize: number;
    lastTradePriceTrHrs?: number;
    lastTradePrice: number;
    lastTradeSize: number;
    lastTradeTick: string;
    lastTradeTime?: string;
    volume: number;
    openPrice: number;
    highPrice: number;
    lowPrice: number;
    delay: boolean;
    isHalted: boolean;
}

export interface IGetMarketQuotesResponse {
    quotes: IQuote[];
}
