// Generated by Copilot
export interface IMarket {
    name: string;
    tradingVenues: string[];
    defaultTradingVenue: string;
    primaryOrderRoutes: string[];
    secondaryOrderRoutes: string[];
    level1Feeds: string[];
    level2Feeds: string[];
    extendedStartTime: string;
    startTime: string;
    endTime: string;
    extendedEndTime: string;
    currency: string;
    snapQuotesLimit: number;
}

export interface IGetMarketsResponse {
    markets: IMarket[];
}
