// Generated by Copilot
export interface ICandle {
    start: string;
    end: string;
    open: number;
    high: number;
    low: number;
    close: number;
    volume: number;
}

export interface IMarketCandlesResponse {
    candles: ICandle[];
}
