// Generated by Copilot
/**
 * Represents a single chain per strike price for symbol options.
 */
export interface IChainPerStrikePrice {
    /** Strike price. */
    strikePrice: number;
    /** Call symbol ID. */
    callSymbolId: number;
    /** Put symbol ID. */
    putSymbolId: number;
}

/**
 * Represents a single chain per root for symbol options.
 */
export interface IChainPerRoot {
    /** Option root symbol. */
    root: string;
    /** Contract multiplier. */
    multiplier: number;
    /** Array of chain per strike price records. */
    chainPerStrikePrice: IChainPerStrikePrice[];
}

/**
 * Represents a single chain per expiry date for symbol options.
 */
export interface IChainPerExpiryDate {
    /** Expiry date (ISO 8601 format). */
    expiryDate: string;
    /** Option description. */
    description: string;
    /** Listing exchange. */
    listingExchange: string;
    /** Option exercise type. */
    optionExerciseType: string;
    /** Array of chain per root records. */
    chainPerRoot: IChainPerRoot[];
}

/**
 * Response object for GET symbols/:id/options containing an array of option chains per expiry date.
 */
export interface IGetSymbolOptionsResponse {
    /** Array of option chains per expiry date. */
    options: IChainPerExpiryDate[];
}
