// Generated by Copilot
export interface IChainPerStrikePrice {
    strikePrice: number;
    callSymbolId: number;
    putSymbolId: number;
}

export interface IChainPerRoot {
    root: string;
    multiplier: number;
    chainPerStrikePrice: IChainPerStrikePrice[];
}

export interface IChainPerExpiryDate {
    expiryDate: string;
    description: string;
    listingExchange: string;
    optionExerciseType: string;
    chainPerRoot: IChainPerRoot[];
}

export interface IGetSymbolOptionsResponse {
    options: IChainPerExpiryDate[];
}
