// Generated by Copilot
import { IUnderlyingMultiplierPair } from './IUnderlyingMultiplierPair';

export interface IOptionContractDeliverables {
    underlyings: IUnderlyingMultiplierPair[];
    cashInLieu: number;
}
