// Generated by Copilot
import { IMinTickData } from './IMinTickData';
import { IOptionContractDeliverables } from './IOptionContractDeliverables';

export interface ISymbolInfo {
  symbol: string;
  symbolId: number;
  description: string;
  securityType: string;
  listingExchange: string;
  minTicks: IMinTickData[];
  optionContractDeliverables?: IOptionContractDeliverables;
  [key: string]: any;
}

export interface IGetSymbolByIdResponse {
  symbols: ISymbolInfo[];
}
