// Generated by Copilot
/**
 * Represents the allowed option types for options contracts.
 *
 * @remarks
 * See: https://www.questrade.com/api/documentation/rest-operations/enumerations/enumerations
 *
 * - 'Call': Call option
 * - 'Put': Put option
 */
export type OptionType = 'Call' | 'Put';
