// Generated by Copilot
export type StrategyType =
    | 'CoveredCall'
    | 'MarriedPuts'
    | 'VerticalCallSpread'
    | 'VerticalPutSpread'
    | 'CalendarCallSpread'
    | 'CalendarPutSpread'
    | 'DiagonalCallSpread'
    | 'DiagonalPutSpread'
    | 'Collar'
    | 'Straddle'
    | 'Strangle'
    | 'ButterflyCall'
    | 'ButterflyPut'
    | 'IronButterfly'
    | 'CondorCall'
    | 'Custom';
